### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by piotr-lwks** [simplesamlphp/simplesamlphp-assets-base#22]
I have the following in my composer.json file:

```
  "require": {
    "simplesamlphp/composer-module-installer": "~1.3",
    "simplesamlphp/simplesamlphp": "2.*",
    "simplesamlphp/simplesamlphp-assets-base": "~2.1",
    "simplesamlphp/simplesamlphp-module-metaedit": "~2.1",
    "simplesamlphp/simplesamlphp-module-metarefresh": "~1.0"
}
```

and 

```
  "config": {
    "allow-plugins": {
      "simplesamlphp/composer-module-installer": true
    }
  }
```

But the `simplesamlphp-assets-base` package would not install with `php composer.phar update`
unless I explicitly install it with `php composer.phar require simplesamlphp/simplesamlphp-assets-base`.
What I am missing?

**Comment by tvdijen** [comment]
What you are missing is the wildcard in the `simplesamlphp/simplesamlphp` requirement..
We have tagged assets v2.1.x, but it is tied to unreleased SSP v2.1.x.
Lower the requirement on assets to ^2.0 and you should be fine
