### ISSUE TITLE
Composer Error - Incorrect Package Name Format

### ISSUE THREAD

**Issue by Veraxus** [simplesamlphp/simplesamlphp-assets-base#23]
Composer has started outputting the following message while installing SimpleSAMLphp...

```
In ModuleInstaller.php line 40:
  Unable to install module simplesamlphp/simplesamlphp-assets-base, package name must be on the form "VENDOR/simplesa
  mlphp-module-MODULENAME".
  ```

**Comment by tvdijen** [comment]
One report for the same issue would have sufficed :)  Closing this one, since it's not related to this repo at all
